CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "BankAccounts" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "AccountNumber" text,
    "Currency" text,
    "Balance" numeric NOT NULL,
    "UserId" bigint NOT NULL,
    "IsActive" boolean NOT NULL,
    "CodePinHash" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "Active" boolean NOT NULL,
    "Deleted" boolean NOT NULL,
    "DeletedBy" integer,
    "DeletedAt" timestamp with time zone,
    "CreatedBy" bigint NOT NULL,
    "UpdatedBy" bigint NOT NULL,
    CONSTRAINT "PK_BankAccounts" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "NickName" text,
    "Avatar" text NOT NULL,
    "Gender" integer,
    "BirthDate" timestamp with time zone,
    "Age" integer NOT NULL,
    "Email" text NOT NULL,
    "UserName" text NOT NULL,
    "Password" text NOT NULL,
    "PhoneNumber" text NOT NULL,
    "Address" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "Active" boolean NOT NULL,
    "Deleted" boolean NOT NULL,
    "DeletedBy" integer,
    "DeletedAt" timestamp with time zone,
    "CreatedBy" bigint NOT NULL,
    "UpdatedBy" bigint NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250927064158_InitDb', '8.0.10');

COMMIT;

